[package]
name = "guess_it"
version = "0.1.0"
authors = ["shaba721"]
edition = "2018"

[dependencies]
rand = "0.6.5"
[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"

branch = "v0.6.x"

